services:
  - type: web
    name: nail-salon-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nail-salon-db
          property: connectionString

databases:
  - name: nail-salon-db
    plan: free
